// swift-tools-version: 5.9
import PackageDescription

// The core, as Swift links it.
//
// Not in CapApp-SPM: that file is regenerated by `cap sync` and says so at the
// top, so anything added there is lost on the next run. This package is ours
// and is referenced from the Xcode project as a local package.
//
// Both of its inputs are built, never committed. `just ios-lib` produces the
// xcframework and copies the generated `dip_ffi.swift` into Sources; the
// .gitignore beside this file keeps them out of the tree.
let package = Package(
    name: "DipFFI",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "DipFFI",
            targets: ["DipFFI"])
    ],
    targets: [
        .binaryTarget(
            name: "DipFFIBinary",
            path: "DipFFI.xcframework"),
        .target(
            name: "DipFFI",
            dependencies: ["DipFFIBinary"])
    ]
)
